// Run as tabbit-cli nodejs stdin; only the isolated QA origin may be reset.
assert.equal(new URL(page.url()).origin, 'http://replica-check.localhost:4174');
const report = { checks: [], viewports: ['1440x900', '390x844'] };
const passed = name => report.checks.push(name);
const closeDialog = async () => { await page.keyboard.press('Escape'); await expect(page.locator('dialog')).toHaveCount(0); };
const battleReady = async () => page.waitForFunction(() => window.__embers.game.scene.getScene('battle').renderHost?.enabled);
await page.evaluate(() => { localStorage.removeItem('embers-of-the-twin-stars-campaign-v2'); localStorage.removeItem('embers-display-settings-v1'); });
await page.setViewportSize({ width: 1440, height: 900 }); await page.reload();
await expect(page.locator('#continue')).toBeDisabled();
await page.locator('#load-menu').click(); await expect(page.locator('dialog')).toContainText('尚无远征记录'); await closeDialog();
await page.locator('#settings-menu').click(); await page.locator('#title-quality').selectOption('low'); await page.locator('#title-motion').check(); await closeDialog();
await page.locator('#settings-menu').click(); await expect(page.locator('#title-quality')).toHaveValue('low'); await expect(page.locator('#title-motion')).toBeChecked();
await page.locator('#title-quality').selectOption('medium'); await page.locator('#title-motion').uncheck(); await closeDialog();
await page.locator('#exit-menu').click(); await expect(page.locator('dialog')).toContainText('关闭当前游戏标签页'); await closeDialog();
passed('主菜单：空档、设置保存、退出说明、Esc');
await page.locator('#start').click();
for (let i = 0; i < 3; i++) await page.getByRole('button', { name: '继续对话', exact: true }).press('Enter');
await page.locator('[data-world-node="village"]').click(); await expect(page.locator('#world-enter')).toBeEnabled(); await page.locator('#world-enter').click();
await page.locator('[data-village-place="exit"]').click(); await expect(page.locator('#village-enter')).toBeEnabled({ timeout: 20000 }); await page.locator('#village-enter').click();
await page.locator('[data-world-node="starfall-bridge"]').click(); await expect(page.locator('#world-enter')).toBeEnabled({ timeout: 20000 }); await page.locator('#world-enter').click();
for (let i = 0; i < 10; i++) {
  await page.waitForFunction(() => document.querySelector('.dialogue,.prep-screen'));
  if (await page.locator('.prep-screen').count()) break;
  await page.getByRole('button', { name: '继续对话', exact: true }).press('Enter');
}
assert.equal(await page.evaluate(() => window.__embers.game.input.keyboard.captures.length), 0);
await page.locator('#formation-skills').click(); await closeDialog();
passed('新游戏 → 世界 → 村庄 → 世界 → 剧情 → 编队；退场释放按键捕获');
await page.locator('.replica-roster [data-inspect="lyra"]').click(); await expect(page.locator('.dossier-heading')).toContainText('莱拉');
await page.locator('#formation-reorder').click(); await page.locator('[data-reorder="-1"]').click(); await expect(page.locator('[aria-label="部署位 1 莱拉"]')).toBeVisible();
await page.locator('[data-sortie="kael"]').uncheck(); await page.locator('#start-battle').click(); await expect(page.locator('.prep-message')).toContainText('主角凯尔必须出击'); await page.locator('[data-sortie="kael"]').check();
await page.locator('[data-item="lyra"]').selectOption('steel-sword'); await page.locator('#start-battle').click(); await expect(page.locator('.prep-message')).toContainText('同一件装备不能分配'); await page.locator('[data-item="lyra"]').selectOption('');
passed('编队：角色切换、顺序调整、主角必选、重复装备拦截');
await page.setViewportSize({ width: 390, height: 844 });
assert.equal(await page.evaluate(() => document.querySelector('.replica-prep').scrollWidth > innerWidth), false);
await page.locator('#formation-skills').click(); await expect(page.locator('dialog')).toBeVisible(); await closeDialog();
await page.locator('#start-battle').click(); await battleReady(); await page.locator('#deploy-battle').click();
for (const id of ['items', 'quests', 'save']) { await page.locator('#battle-menu').click(); await page.locator('[data-battle-menu=' + id + ']').click(); await expect(page.locator('dialog')).toBeVisible(); await closeDialog(); }
await page.locator('#battle-menu').click(); await page.locator('[data-battle-menu=party]').click(); await expect(page.locator('[data-sortie="kael"]')).toBeDisabled(); await page.locator('#prep-back').click(); await page.locator('.replica-battle').waitFor();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.locator('#battle-menu').click(); await page.locator('[data-battle-menu=system]').click(); await page.locator('[data-render-setting="reducedMotion"]').check(); await page.locator('#render-settings-close').click();
await page.locator('#battle-menu').click(); await page.locator('[data-battle-menu=system]').click(); assert.equal(await page.locator('.render-settings').evaluate(el => getComputedStyle(el).animationName), 'none'); await page.locator('[data-render-setting="reducedMotion"]').uncheck(); await page.locator('#render-settings-close').click();
passed('390×844：编队滚动和出战、战场菜单、只读编队返回、减少动态效果、无横向溢出');
await page.setViewportSize({ width: 1440, height: 900 });
const kaelPoint = await page.evaluate(() => { const scene = window.__embers.game.scene.getScene('battle'), unit = scene.units.find(u => u.id === 'kael'); return scene.renderHost.debug().points.find(p => p.id === `${unit.x},${unit.y}`); }); await page.mouse.click(kaelPoint.x, kaelPoint.y); await page.locator('#detail').click(); await page.locator('#detail-close').click();
const before = await page.evaluate(() => JSON.stringify(window.__embers.game.scene.getScene('battle').units));
await page.locator('#battle-menu').click(); await page.locator('[data-battle-menu=map]').click(); await page.locator('#render-toggle').click(); await expect(page.locator('#render-toggle')).toBeEnabled(); await page.locator('#render-toggle').click(); await battleReady(); await page.locator('#close-battle-tools').click();
assert.equal(await page.evaluate(() => JSON.stringify(window.__embers.game.scene.getScene('battle').units)), before);
await page.locator('#end').click(); await page.waitForFunction(() => { const s = window.__embers.game.scene.getScene('battle'); return s.turn === 2 && s.mode === 'idle'; }, null, { timeout: 45000 });
const saved = await page.evaluate(() => JSON.stringify(window.__embers.game.scene.getScene('battle').units));
await page.reload(); await page.locator('#load-menu').click(); await page.locator('#load-current').click(); await battleReady();
assert.equal(await page.evaluate(() => JSON.stringify(window.__embers.game.scene.getScene('battle').units)), saved);
passed('桌面战场：角色详情、经典/3D 状态一致、敌方回合、读取存档恢复');
await page.reload(); await page.locator('#start').click(); await page.locator('#new-cancel').click(); await expect(page.locator('#continue')).toBeEnabled();
await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#formation-menu').click(); await page.locator('#prep-back').click(); await page.locator('#continue').click(); await battleReady();
passed('主菜单：取消覆盖保留存档、手机编队入口返回、继续远征');
report.errors = (await page.pageErrors()).map(e => e.message); assert.equal(report.errors.length, 0);
report.date = new Date().toISOString(); globalThis.replicaReport = report;
const path = artifactPath('replica-browser-report.json'); await (await import('node:fs/promises')).writeFile(path, JSON.stringify(report, null, 2));
return { path, ...report };
